### ISSUE TITLE
Why twice the number of pulses?

### ISSUE THREAD

**Issue by mstevens83** [bencholmes/heartbeat#1]
#Hello,
I was wondering why you let the for-loop loop for twice the number of beats?https://github.com/bencholmes/heartbeat/blob/3233ba233ad568e7a7d522ad0db23bd35a9a482c/heartbeat.m#L32
1 pulse is 1 beat, right? So won't you end up with twice the number of requested beats in the wave file?

**Comment by bencholmes** [comment]
Hi Matthias,

I'm actually using two different definitions of the term 'beat' in my head. I think of a heart beat as a 'dum-dum' sound, two pulses stuck together, so to get from the number of beats specified by the user to the number produced I multiply it by two. 

This may not be the scientific/medical way of how a heart works (maybe it's just one pulse that produces both sounds) but the project detoured from that to simply producing a pleasing audio result.

You will find at the bottom of the loop a section of code that differentiates between two beats and adds one of two time periods, one for the short wait before the second pulse, and one long wait before the next beat.
```
    % A condition to switch between two different lengths between pulses,
    % and apply a gain difference.
    if mod(n,2)
        % 1/4 of the length
        inter_pulse = zeros(1, ceil((((total_dur)*fs) - 2*pulse_Ns)/4) );
        gain = 0.8;
    else
        % 3/4 of the length
        inter_pulse = zeros(1, floor(3*(((total_dur)*fs) - 2*pulse_Ns)/4) );
        gain = 1;
    end
```

If you'd really like me to fix the code to make more sense I can, but really it's just a fun heuristic method of generating something vaguely heartbeat sounding ;)

**Comment by mstevens83** [comment]
Hi Ben,
Thanks for the quick response!
Maybe I should also give some context. I'm currently trying to convert your code from Matlab to Java for use in an Android application. The idea behind the app is to allow users to listen to their own heartbeat. The app would connect to a to use a wearable heartrate sensor (e.g. Polar) via Bluetooth to get a stream of BPM values (probably at 1Hz), and would then generate (in real-time) a synthetic heartbeat audio signal with matching BPM.
My purposes aren't strictly medical either, although some of the people involved in the project may care more than I do. Hence the 2-pulse per beat thing may be a bit too loose of an approach, unless I can properly explain what it means. Still, your code is excellent starting point. So if you are interested in make it more "correct" that would be great and perhaps I can help.
Also, what is the rationale for the varying wait between the 2 pulses?
Best,
Matthias

**Comment by bencholmes** [comment]
Hi Matthias,

I have overhauled the script into something somewhat legible. I never really anticipated anyone using this code... Let me know if you need further clarification on anything!

I'm going to mark this as closed since there is no longer the multiply by two. The code has been modularised into Script -> singleHeartBeat -> singlePulse so that it is clear that 1 heartbeat = 2 pulses, and that there are two different durations in between the pulses.

Good luck with your project!

Best,
Ben

**Comment by mstevens83** [comment]
Thanks a lot!
