### ISSUE TITLE
No longer applying a gain difference

### ISSUE THREAD

**Issue by mstevens83** [bencholmes/heartbeat#2]
Is there a particular reason you no longer apply a gain difference to the pulses in v2.0?
In v1.0 you alternated between 0.8 and 1.0 as a gain multiplier: https://github.com/bencholmes/heartbeat/blob/3233ba233ad568e7a7d522ad0db23bd35a9a482c/heartbeat.m#L87

In v2.0 this seem to be gone: https://github.com/bencholmes/heartbeat/blob/49b77d87bb03fb7b03240cda21762e1311ef077a/singleHeartBeat.m#L18

Also, am I right that the net effect of the gain difference was that the first pulse of every pair would be about 80% of the loudness of the 2nd pulse?

**Comment by bencholmes** [comment]
This was simply me being a dum dum. There is no unit testing to speak of so when I was trying to clarify the code I rushed through and have made a mistake which wasn’t caught.

You are absolutely correct in your assumption, it was a choice to give the beat a nice sounding rhythm.

**Comment by bencholmes** [comment]
Fixed in latest commit:

https://github.com/bencholmes/heartbeat/blob/2a94f3ba40f2ed0381928c6ebae799e7b391ec9a/singleHeartBeat.m#L18

Hope your project is going well, Matthias!

**Comment by mstevens83** [comment]
Thanks! The project is going quite well. Almost done porting everything to Java. Only the Butterworth enn iirpeak filter are left to do. I'm try to use https://github.com/berndporr/iirj for that but still working out which methods/parameters correspond to the MATLAB functions you use.
When I'm done I'll post the Java port on GitHub as well and link to your repo.
Cheers,
Matthias

**Comment by bencholmes** [comment]
No worries about linking back it's CC0, no attribution needed!

As for the filters, here are what they look like:

![filters-image](https://user-images.githubusercontent.com/12434867/42022302-43859106-7abd-11e8-8d49-8944bba12333.png)

The third order butterworth is probably easiest with a high pass into a low pass, with parameters like
    
    butterworth.lowPass(3,Samplingfreq,140+tempo);
    butterworth.highPass(3,Samplingfreq,20);

And for the peaking filter

    butterworth.bandPass(2,Samplingfreq,110,120);

But don't worry about precise values! Just make it sound good.

**Comment by mstevens83** [comment]
Tadah: https://github.com/imec-apt/heartbeat
